import { Bot, Check, ChevronDown, LoaderCircle, MapPin, MessageCircle, Send, Sparkles, X } from 'lucide-react'
import { useState } from 'react'
import { useAuth } from '../contexts/AuthContext'
import { useLanguage } from '../contexts/LanguageContext'
import { createBooking, createFarmerRequest, getMachines, sendChatMessage } from '../services/api'
import { Button } from './Ui'

type ChatMessage = { id: number; from: 'assistant' | 'user'; text: string }
type ChatContext = Record<string, unknown>

export function ChatAssistant() {
  const { user } = useAuth(); const { language, tr } = useLanguage(); const [open, setOpen] = useState(false); const [input, setInput] = useState(''); const [sending, setSending] = useState(false); const [context, setContext] = useState<ChatContext>({}); const [draftReady, setDraftReady] = useState(false); const [messages, setMessages] = useState<ChatMessage[]>([{ id: 1, from: 'assistant', text: tr('Hi, I’m FleetBot. I can arrange a machine, explain the rate, find the field, or negotiate a quote.') }]); const [saved, setSaved] = useState('')
  if (!user) return null
  const isFarmer = user.role === 'FARMER'
  function localizeResponse(message: string, result: { context: ChatContext; draftReady?: boolean }) { if (language !== 'ta') return message; const current = result.context; if (result.draftReady && current.machineType && current.areaInAcres && current.village) return `உங்கள் ${tr(String(current.machineType))} பணி ${current.areaInAcres} ஏக்கர், ${current.village}, ${current.field || 'வயல்'} பகுதியில் ${current.preferredDate || 'தேர்ந்த தேதியில்'} திட்டமிடப்பட்டுள்ளது. மதிப்பீடு ₹${Number(current.quote || 0).toLocaleString('en-IN')}. இதை அட்டவணைப்படுத்தவா?`; if (/discount|revised estimate|route discount/i.test(message)) return `8% பாதைத் தள்ளுபடியை வழங்கலாம். திருத்தப்பட்ட மதிப்பீடு ₹${Number(current.quote || 0).toLocaleString('en-IN')}.`; if (/estimated at|estimate is/i.test(message)) return `${tr(String(current.machineType || 'tractor'))} பணிக்கான மதிப்பீடு ₹${Number(current.quote || 0).toLocaleString('en-IN')}. தொடரவா அல்லது கட்டணத்தைப் பேசவா?`; return tr(message) }
  async function send(text = input) { const value = text.trim(); if (!value || sending) return; if (/schedule this job|yes, schedule|approve.*schedule|confirm booking/i.test(value) && draftReady) { await confirmBooking(); return } if (/change details|start over|reset/i.test(value)) { setContext({}); setDraftReady(false); setMessages((current) => [...current, { id: Date.now(), from: 'user', text: value }, { id: Date.now() + 1, from: 'assistant', text: tr('No problem. Let’s start a fresh booking. Which machine do you need?') }]); setInput(''); return } setMessages((current) => [...current, { id: Date.now(), from: 'user', text: value }]); setInput(''); setSending(true); try { const result = await sendChatMessage(value, context); setContext(result.context); setDraftReady(Boolean(result.draftReady)); setMessages((current) => [...current, { id: Date.now() + 1, from: 'assistant', text: localizeResponse(result.message, result) }]) } finally { setSending(false) } }
  async function confirmBooking() { if (!context.machineType || !context.areaInAcres || !context.preferredDate || !context.village) return; setSending(true); try { if (isFarmer) { await createFarmerRequest({ machineType: String(context.machineType), areaInAcres: Number(context.areaInAcres), preferredDate: String(context.preferredDate), location: { village: String(context.village), field: String(context.field || 'Field'), landmark: String(context.landmark || '') }, status: 'PENDING' }); setSaved(tr('Request sent to your CHC.')) } else { const machines = await getMachines(); const machine = machines.find((item) => item.type === context.machineType) || machines[0]; await createBooking({ farmerName: String(context.farmerName || 'Farmer'), phone: String(context.phone || ''), machineId: machine?.id || `m-${String(context.machineType)}`, machineType: String(context.machineType), areaInAcres: Number(context.areaInAcres), location: { village: String(context.village), field: String(context.field || 'Field'), landmark: String(context.landmark || '') }, scheduledStart: `${String(context.preferredDate)}T07:30:00`, scheduledEnd: `${String(context.preferredDate)}T09:30:00`, specialInstructions: `Chat quote: ₹${Number(context.quote || 0).toLocaleString('en-IN')}`, status: 'PENDING' }); setSaved(tr('Booking created on the CHC run sheet.')) } setMessages((current) => [...current, { id: Date.now(), from: 'assistant', text: tr('All set. I’ve saved the request and kept the quote with it. You can continue editing the full booking from the bookings page.') }]); setDraftReady(false) } catch { setMessages((current) => [...current, { id: Date.now(), from: 'assistant', text: tr('I could not save that yet. Please check the machine and field details, then try again.') }]) } finally { setSending(false) } }
  const quickReplies = context.machineType ? ['Check prices', 'Negotiate rate'] : ['Book a tractor', 'Check prices']
  return <><button className={`chat-launcher ${open ? 'is-open' : ''}`} onClick={() => setOpen((value) => !value)} aria-label={open ? 'Close FleetBot' : 'Open FleetBot'}>{open ? <X size={21} /> : <MessageCircle size={21} />}<span>FleetBot</span></button>{open && <section className="chat-panel" aria-label="FleetBot booking assistant"><header className="chat-head"><div className="chat-title"><span className="bot-mark"><Bot size={18} /></span><div><strong>FleetBot</strong><small>Booking & rate assistant <span className="online-dot" /></small></div></div><button className="chat-close" onClick={() => setOpen(false)} aria-label="Close chatbot"><ChevronDown size={18} /></button></header><div className="chat-body">{messages.map((message) => <div className={`chat-message ${message.from}`} key={message.id}><span>{message.text}</span></div>)}{sending && <div className="chat-message assistant"><span className="typing"><i /><i /><i /></span></div>}{draftReady && <div className="chat-draft"><div><Sparkles size={15} /><strong>{isFarmer ? 'Ready to send request' : 'Ready to schedule'}</strong></div><p><strong className="capitalize">{String(context.machineType)}</strong> · {String(context.areaInAcres)} acres · <MapPin size={12} /> {String(context.village)}</p><div className="chat-quote"><span>Estimated total</span><strong>₹{Number(context.quote || 0).toLocaleString('en-IN')}</strong></div><Button onClick={confirmBooking} disabled={sending}><Check size={15} />{isFarmer ? 'Send request' : 'Schedule job'}</Button></div>}{saved && <div className="chat-saved"><Check size={14} />{saved}</div>}</div><div className="chat-quick">{quickReplies.map((reply) => <button key={reply} onClick={() => send(reply)}>{reply}</button>)}</div><form className="chat-input" onSubmit={(event) => { event.preventDefault(); send() }}><input value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask about a machine, rate, or booking..." aria-label="Message FleetBot" /><button type="submit" disabled={!input.trim() || sending} aria-label="Send message">{sending ? <LoaderCircle className="spin" size={17} /> : <Send size={17} />}</button></form><footer className="chat-foot">FleetBot uses CHC rate cards and route allowances. Final price is confirmed by the CHC.</footer></section>}</>
}
