import { MapPin, Navigation } from 'lucide-react'
import { useEffect, useRef, useState, type CSSProperties } from 'react'
import type { OperatorLocation } from '../types'

interface MapPolyline { path: Array<{ lat: number; lng: number }>; color?: string }
interface GoogleMapsApi { maps?: { Map: new (element: HTMLElement, options: unknown) => unknown; Marker: new (options: unknown) => unknown; Polyline: new (options: unknown) => unknown } }

export function MapComponent({ center, markers = [], polylines = [], path = [] }: { center: { lat: number; lng: number }; markers?: Array<{ lat: number; lng: number; label: string }>; polylines?: MapPolyline[]; path?: OperatorLocation[] }) {
  const mapRef = useRef<HTMLDivElement>(null); const [liveMap, setLiveMap] = useState(false); const visiblePolylines = polylines.length ? polylines : path.length ? [{ path }] : []; const markerKey = JSON.stringify(markers); const polylineKey = JSON.stringify(visiblePolylines)
  useEffect(() => { const key = import.meta.env.VITE_GOOGLE_MAPS_API_KEY; if (!key || !mapRef.current) return; const mount = () => { const google = (window as unknown as { google?: GoogleMapsApi }).google; const maps = google?.maps; if (!maps?.Map || !maps.Marker || !maps.Polyline || !mapRef.current) return; const map = new maps.Map(mapRef.current, { center, zoom: 14, mapTypeId: 'roadmap' }); markers.forEach((marker) => new maps.Marker({ map, position: { lat: marker.lat, lng: marker.lng }, title: marker.label })); visiblePolylines.forEach((line) => new maps.Polyline({ map, path: line.path, strokeColor: line.color || '#e36b2c', strokeOpacity: .8, strokeWeight: 4 })); setLiveMap(true) }; const existing = document.querySelector('script[data-farmfleet-maps]'); if (existing) { existing.addEventListener('load', mount); mount() } else { const script = document.createElement('script'); script.src = `https://maps.googleapis.com/maps/api/js?key=${key}`; script.async = true; script.dataset.farmfleetMaps = 'true'; script.onload = mount; document.head.appendChild(script) } }, [center.lat, center.lng, markerKey, polylineKey])
  return <div className="map-component" style={{ '--map-lat': center.lat, '--map-lng': center.lng } as CSSProperties}><div ref={mapRef} className="google-map-canvas" style={{ display: liveMap ? 'block' : 'none' }} />{!liveMap && <><div className="map-grid" /><div className="map-road road-a" /><div className="map-road road-b" /><div className="map-center"><Navigation size={25} /><span>Map preview</span><small>{visiblePolylines.length ? `${visiblePolylines[0].path.length} location updates` : 'Add VITE_GOOGLE_MAPS_API_KEY for live map tiles'}</small></div>{markers.map((marker, index) => <div className="map-marker" key={`${marker.label}-${index}`} style={{ left: `${35 + index * 24}%`, top: `${36 + index * 16}%` }}><MapPin size={25} /><span>{marker.label}</span></div>)}</>}</div>
}
