import { MapPin, Navigation } from 'lucide-react'
import { useEffect, useRef, useState, type CSSProperties } from 'react'
import type { OperatorLocation } from '../types'

export function MapComponent({ center, markers = [], path = [] }: { center: { lat: number; lng: number }; markers?: Array<{ lat: number; lng: number; label: string }>; path?: OperatorLocation[] }) {
  const mapRef = useRef<HTMLDivElement>(null); const [liveMap, setLiveMap] = useState(false)
  useEffect(() => { const key = import.meta.env.VITE_GOOGLE_MAPS_API_KEY; if (!key || !mapRef.current) return; const mount = () => { const google = (window as unknown as { google?: { maps?: { Map: new (element: HTMLElement, options: unknown) => unknown } } }).google; if (!google?.maps?.Map || !mapRef.current) return; new google.maps.Map(mapRef.current, { center, zoom: 14, mapTypeId: 'roadmap' }); setLiveMap(true) }; const existing = document.querySelector('script[data-farmfleet-maps]'); if (existing) { existing.addEventListener('load', mount); mount() } else { const script = document.createElement('script'); script.src = `https://maps.googleapis.com/maps/api/js?key=${key}`; script.async = true; script.dataset.farmfleetMaps = 'true'; script.onload = mount; document.head.appendChild(script) } }, [center.lat, center.lng])
  return <div className="map-component" style={{ '--map-lat': center.lat, '--map-lng': center.lng } as CSSProperties}>{liveMap && <div ref={mapRef} className="google-map-canvas" />}{!liveMap && <><div className="map-grid" /><div className="map-road road-a" /><div className="map-road road-b" /><div className="map-center"><Navigation size={25} /><span>Map preview</span><small>{path.length ? `${path.length} location updates` : 'Add VITE_GOOGLE_MAPS_API_KEY for live map tiles'}</small></div>{markers.map((marker, index) => <div className="map-marker" key={`${marker.label}-${index}`} style={{ left: `${35 + index * 24}%`, top: `${36 + index * 16}%` }}><MapPin size={25} /><span>{marker.label}</span></div>)}</>}</div>
}
