import { demoBookings, demoMachines, demoNotifications, demoProposal, demoRequests, demoTasks, demoUser, demoUsers } from '../data'
import type { Booking, FarmerBooking, FarmerNotification, FarmerProfile, FarmerRequest, Machine, Recommendation, ScheduleProposal, User } from '../types'

const API_URL = import.meta.env.VITE_API_URL || '/api'

async function request<T>(path: string, options: RequestInit = {}): Promise<T> {
  const token = localStorage.getItem('farmfleet_token')
  const isMultipart = options.body instanceof FormData
  const response = await fetch(`${API_URL}${path}`, { ...options, headers: { ...(isMultipart ? {} : { 'Content-Type': 'application/json' }), ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) } })
  if (!response.ok) throw new Error((await response.json().catch(() => null))?.message || 'Request failed')
  return response.json()
}

export async function login(email: string, password: string): Promise<{ token: string; user: User }> {
  try { return await request('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }) }
  catch { const user = demoUsers.find((account) => account.email === email); if (user && password === 'password123') return { token: 'demo-token', user }; throw new Error('Use a FarmFleet demo account with password123.') }
}
export async function updateProfile(payload: { name?: string; email?: string; phone?: string; currentPassword?: string; newPassword?: string }): Promise<User> { const result = await request<{ user: User }>('/auth/profile', { method: 'PATCH', body: JSON.stringify(payload) }); return result.user }
export async function getBookings(): Promise<Booking[]> { try { return await request('/bookings') } catch { return demoBookings } }
export async function getMachines(): Promise<Machine[]> { try { return await request('/machines') } catch { return demoMachines } }
export async function createBooking(payload: Partial<Booking>): Promise<Booking> { try { return await request('/bookings', { method: 'POST', body: JSON.stringify(payload) }) } catch { return { ...demoBookings[0], ...payload, id: `BK-${Date.now().toString().slice(-4)}` } as Booking } }
export async function updateBooking(id: string, payload: Partial<Booking>): Promise<Booking> { try { return await request(`/bookings/${id}`, { method: 'PATCH', body: JSON.stringify(payload) }) } catch { return { ...demoBookings.find((booking) => booking.id === id), ...payload } as Booking } }
export async function cancelBooking(id: string): Promise<void> { try { await request(`/bookings/${id}`, { method: 'DELETE' }) } catch { /* demo mode */ } }
export async function getRecommendations(params: { machineId: string; date: string; area: number; location: string }): Promise<Recommendation[]> { try { return await request(`/schedule/recommend-slots?machineId=${params.machineId}&preferredDate=${params.date}&areaInAcres=${params.area}&location=${encodeURIComponent(params.location)}`) } catch { return [{ startTime: '07:30', endTime: '09:30', reason: 'Groups with nearby jobs' }, { startTime: '10:00', endTime: '12:00', reason: 'Minimizes travel distance' }, { startTime: '15:30', endTime: '17:30', reason: 'Fits before the evening route' }] } }
export async function getProposal(): Promise<ScheduleProposal | null> { try { return await request('/schedule/proposals/current') } catch { return demoProposal } }
export async function acceptProposal(proposalId: string): Promise<void> { try { await request('/schedule/accept-reschedule', { method: 'POST', body: JSON.stringify({ proposalId }) }) } catch { /* demo mode */ } }
export async function getFarmerProfile(): Promise<FarmerProfile> { try { return await request('/farmer/profile') } catch { return { ...demoUser, id: 'usr-farmer', name: 'Rajesh Singh', email: 'rajesh@farmfleet.in', role: 'FARMER', village: 'Bairiya', address: 'Plot 19, Meerut', createdAt: '2024-11-02' } } }
export async function updateFarmerProfile(payload: { name?: string; village?: string; address?: string; phone?: string; currentPassword?: string; newPassword?: string }): Promise<FarmerProfile> { try { return await request('/farmer/profile', { method: 'PATCH', body: JSON.stringify(payload) }) } catch { return { ...demoUser, ...payload, id: 'usr-farmer', name: payload.name || 'Rajesh Singh', email: 'rajesh@farmfleet.in', role: 'FARMER', village: payload.village || 'Bairiya', address: payload.address || 'Plot 19, Meerut', createdAt: '2024-11-02' } as FarmerProfile } }
export async function getFarmerRequests(filters: { status?: string; from?: string; to?: string } = {}): Promise<FarmerRequest[]> { try { const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value) as string[][]).toString(); return await request(`/farmer/requests${params ? `?${params}` : ''}`) } catch { return demoRequests.filter((item) => (!filters.status || item.status === filters.status) && (!filters.from || item.preferredDate >= filters.from) && (!filters.to || item.preferredDate <= filters.to)) } }
export async function getFarmerRequest(id: string): Promise<FarmerRequest> { try { return await request(`/farmer/requests/${id}`) } catch { return demoRequests.find((item) => item.id === id) || demoRequests[0] } }
export async function createFarmerRequest(payload: Partial<FarmerRequest> & { preferredTimeWindow?: string; specialInstructions?: string; cropType?: string }): Promise<FarmerRequest> { try { return await request('/farmer/requests', { method: 'POST', body: JSON.stringify(payload) }) } catch { return { ...demoRequests[0], ...payload, id: `REQ-${Date.now().toString().slice(-3)}` } as FarmerRequest } }
export async function getFarmerBookings(filters: { status?: string; from?: string; to?: string } = {}): Promise<FarmerBooking[]> { try { const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value) as string[][]).toString(); return await request(`/farmer/bookings${params ? `?${params}` : ''}`) } catch { return demoBookings.map((item) => ({ id: item.id, machineType: item.machineType, machineName: item.machineType, scheduledStart: item.scheduledStart, scheduledEnd: item.scheduledEnd, status: item.status, areaInAcres: item.areaInAcres, location: item.location, operatorName: item.operatorName, operator: item.operatorName ? { name: item.operatorName, phone: '' } : null, specialInstructions: item.specialInstructions })) } }
export async function getFarmerBooking(id: string): Promise<FarmerBooking> { try { return await request(`/farmer/bookings/${id}`) } catch { const item = demoBookings.find((booking) => booking.id === id) || demoBookings[0]; return { id: item.id, machineType: item.machineType, machineName: item.machineType, scheduledStart: item.scheduledStart, scheduledEnd: item.scheduledEnd, status: item.status, areaInAcres: item.areaInAcres, location: item.location, operatorName: item.operatorName, operator: item.operatorName ? { name: item.operatorName, phone: '' } : null, specialInstructions: item.specialInstructions } } }
export async function cancelFarmerBooking(id: string): Promise<void> { try { await request(`/farmer/bookings/${id}/cancel`, { method: 'POST' }) } catch { /* prototype mode */ } }
export async function getFarmerNotifications(unreadOnly = false): Promise<FarmerNotification[]> { try { return await request(`/farmer/notifications${unreadOnly ? '?unreadOnly=true' : ''}`) } catch { return demoNotifications.filter((item) => !unreadOnly || !item.read) } }
export async function markFarmerNotificationRead(id: string): Promise<void> { try { await request(`/farmer/notifications/${id}/read`, { method: 'PATCH' }) } catch { /* demo mode */ } }
export async function getOperatorTasks(): Promise<Booking[]> { try { return await request('/operator/tasks') } catch { return demoTasks } }
export async function updateOperatorTask(id: string, payload: Partial<Booking>): Promise<Booking> { try { return await request(`/operator/tasks/${id}`, { method: 'PATCH', body: JSON.stringify(payload) }) } catch { return { ...demoTasks.find((task) => task.id === id), ...payload } as Booking } }
export async function processVoice(file: File, transcript = '', sourceLanguage = 'en-IN'): Promise<{ voiceRecordingId: string; extractedData: Record<string, string | number>; transcript?: string }> {
  const body = new FormData(); body.append('audio', file); if (transcript) body.append('transcript', transcript); body.append('sourceLanguage', sourceLanguage)
  try { return await request('/voice-booking/process', { method: 'POST', body, headers: {} }) } catch { const english = sourceLanguage.toLowerCase().startsWith('ta') ? translateTamilLocally(transcript) : transcript; return { voiceRecordingId: 'voice-demo', extractedData: { farmerName: 'Sita Kumari', phone: '+91 98990 11223', machineType: english.toLowerCase().includes('sprayer') ? 'sprayer' : english.toLowerCase().includes('rotavator') ? 'rotavator' : 'tractor', areaInAcres: Number(english.match(/(\d+(?:\.\d+)?)\s*(?:acre|acres)/i)?.[1] || 4), preferredDate: '2025-01-18', timeWindow: '07:30 - 09:30', village: 'Bairiya', field: 'South field', landmark: 'Near the tube well', notes: english || 'Please call on arrival', translatedTranscript: english } } }
}
function translateTamilLocally(text: string) { const terms: Array<[string, string]> = [['டிராக்டர்', 'tractor'], ['ரோட்டாவேட்டர்', 'rotavator'], ['விதைப்பான்', 'seeder'], ['தெளிப்பான்', 'sprayer'], ['அறுவடை இயந்திரம்', 'harvester'], ['ஏக்கர்', 'acres'], ['கிராமம்', 'village'], ['வயல்', 'field'], ['நிலப்பகுதி', 'plot'], ['அருகில்', 'near'], ['நாளை', 'tomorrow'], ['காலை', 'morning'], ['மாலை', 'evening'], ['வேண்டும்', 'requested'], ['தேவை', 'need']]; return terms.reduce((value, [source, target]) => value.split(source).join(` ${target} `), text).replace(/\s+/g, ' ').trim() }
export async function confirmVoice(voiceRecordingId: string, extractedData: Record<string, unknown>): Promise<void> { try { await request('/voice-booking/confirm', { method: 'POST', body: JSON.stringify({ voiceRecordingId, extractedData }) }) } catch { /* demo mode */ } }
export async function rejectVoice(voiceRecordingId: string): Promise<void> { try { await request('/voice-booking/reject', { method: 'POST', body: JSON.stringify({ voiceRecordingId }) }) } catch { /* demo mode */ } }
export async function sendChatMessage(message: string, context: Record<string, unknown>): Promise<{ message: string; quickReplies: string[]; context: Record<string, unknown>; draftReady?: boolean }> { try { return await request('/chat/message', { method: 'POST', body: JSON.stringify({ message, context }) }) } catch { return localChatResponse(message, context) } }

function localChatResponse(message: string, context: Record<string, unknown>) { const lower = message.toLowerCase(); const next = { ...context }; const machine = ['tractor', 'rotavator', 'seeder', 'sprayer', 'harvester'].find((type) => lower.includes(type)); const acres = message.match(/(\d+(?:\.\d+)?)\s*(?:acre|acres)/i)?.[1]; const village = message.match(/(?:in|at|near|village)\s+([a-z][a-z -]{2,28})/i)?.[1]?.trim(); const dateMatch = message.match(/(?:(?:on|for)\s+)?(\d{1,2})(?:st|nd|rd|th)?\s*(january|february|march|april|may|june|july|august|september|october|november|december)/i); const date = dateMatch ? new Date(`${dateMatch[2]} ${dateMatch[1]}, 2025`).toISOString().slice(0, 10) : /tomorrow/i.test(lower) ? new Date(Date.now() + 86400000).toISOString().slice(0, 10) : undefined; const field = message.match(/(?:plot|field)\s*([A-Za-z0-9][A-Za-z0-9 -]{1,20})/i)?.[1]?.trim(); if (machine) next.machineType = machine; if (acres) next.areaInAcres = Number(acres); if (village) next.village = village.replace(/\s+(for|on|tomorrow|today).*$/i, '').trim(); if (date) next.preferredDate = date; if (field) next.field = field; if (/negotiate|lower|discount|कम/i.test(lower) && next.quote) { next.quote = Math.round(Number(next.quote) * .92); return { message: `I can apply an 8% route discount. Your revised estimate is ₹${Number(next.quote).toLocaleString('en-IN')}.`, quickReplies: ['Schedule this job', 'Change details'], context: next, draftReady: true }; } if (!next.machineType) return { message: 'Which machine do you need? I can arrange a tractor, rotavator, seeder, sprayer, or harvester.', quickReplies: ['Tractor', 'Rotavator', 'Sprayer'], context: next }; if (!next.areaInAcres) return { message: 'How many acres should the machine cover?', quickReplies: [], context: next }; if (!next.preferredDate) return { message: 'What date should I plan it for? Try “20 January”.', quickReplies: ['Tomorrow', '20 January'], context: next }; if (!next.village) return { message: 'Which village is the field in?', quickReplies: ['Bairiya village'], context: next }; if (!next.field) return { message: 'What is the field or plot name?', quickReplies: ['Plot 12B'], context: next }; const quote = Number(next.areaInAcres) * ({ tractor: 950, rotavator: 720, seeder: 680, sprayer: 540, harvester: 1450 }[String(next.machineType)] || 950) + 180; next.quote = quote; return { message: `Your ${next.machineType} job is estimated at ₹${quote.toLocaleString('en-IN')}. Shall I schedule it?`, quickReplies: ['Schedule this job', 'Negotiate rate'], context: next, draftReady: true }; }
