import { prisma } from '../lib/prisma.js'
import type { BookingStatus, Role } from '@prisma/client'
import { jobDurationPredictor } from './ai/jobDurationPredictor.js'
import { recordTrainingSample } from './trainingService.js'
import { AppError } from '../utils/errors.js'
import type { z } from 'zod'
import type { bookingSchema, bookingUpdateSchema } from '../utils/validation.js'
type BookingInput = z.infer<typeof bookingSchema>; type BookingUpdate = z.infer<typeof bookingUpdateSchema>
export async function listBookings(user: { id: string; role: Role; chclId?: string | null }, filters: { status?: BookingStatus; date?: string; dateFrom?: string; dateTo?: string; machine?: string; farmer?: string }) { const where: any = {}; if (user.role === 'FARMER') where.farmerId = user.id; if (user.role === 'OPERATOR') where.operatorId = user.id; if (user.chclId && user.role !== 'FARMER' && user.role !== 'OPERATOR') where.machine = { chclId: user.chclId }; if (filters.status) where.status = filters.status; if (filters.machine) where.machineId = filters.machine; if (filters.farmer) where.farmerId = filters.farmer; if (filters.date) { const day = new Date(filters.date); const next = new Date(day); next.setDate(next.getDate() + 1); where.scheduledStart = { gte: day, lt: next } } else if (filters.dateFrom || filters.dateTo) { where.scheduledStart = { ...(filters.dateFrom ? { gte: new Date(filters.dateFrom) } : {}), ...(filters.dateTo ? { lt: new Date(new Date(filters.dateTo).getTime() + 86400000) } : {}) } } const bookings = await prisma.booking.findMany({ where, include: { farmer: { select: { name: true, phone: true } }, machine: true, operator: { select: { name: true } } }, orderBy: { scheduledStart: 'asc' } }); return bookings.map(toBookingDto) }
export function toBookingDto(booking: any) { return { ...booking, farmerName: booking.farmer?.name, phone: booking.farmer?.phone, machineType: booking.machine?.type, machineName: booking.machine?.name, operatorName: booking.operator?.name, farmer: undefined, machine: undefined, operator: undefined } }
async function resolveFarmer(input: BookingInput, chclId?: string | null) { if (input.farmerId) return input.farmerId; if (!input.phone || !input.farmerName) throw new AppError(400, 'FARMER_REQUIRED', 'farmerId or farmerName and phone are required.'); const existing = await prisma.user.findFirst({ where: { phone: input.phone, role: 'FARMER' } }); if (existing) return existing.id; const generatedEmail = `${input.phone.replace(/\D/g, '')}@farmer.farmfleet.local`; return (await prisma.user.create({ data: { name: input.farmerName, phone: input.phone, email: generatedEmail, role: 'FARMER', passwordHash: 'managed-by-chc', chclId } })).id }
export async function createBooking(input: BookingInput, chclId?: string | null) { const farmerId = await resolveFarmer(input, chclId); const predicted = input.predictedDurationMinutes ? { predictedDurationMinutes: input.predictedDurationMinutes } : await jobDurationPredictor.predict({ machineType: input.machineType || 'tractor', areaInAcres: input.areaInAcres, cropType: input.cropType }); return prisma.booking.create({ data: { farmerId, machineId: input.machineId, operatorId: input.operatorId || undefined, areaInAcres: input.areaInAcres, cropType: input.cropType, location: input.location, scheduledStart: input.scheduledStart, scheduledEnd: input.scheduledEnd, status: input.status || 'PENDING', specialInstructions: input.specialInstructions, predictedDurationMinutes: predicted.predictedDurationMinutes }, include: { farmer: true, machine: true, operator: true } }).then(toBookingDto) }
export async function updateBooking(id: string, input: BookingUpdate) { const { farmerName: _farmerName, phone: _phone, machineType: _machineType, ...data } = input; const updated = await prisma.booking.update({ where: { id }, data, include: { farmer: true, machine: true, operator: true } }); if (updated.actualStart && updated.actualEnd) await recordTrainingSample(updated); return toBookingDto(updated) }
