import { prisma } from '../lib/prisma.js'
import { Prisma } from '@prisma/client'
import { notifyBookingEvent, notifyFarmer } from './notificationService.js'
import { dynamicRescheduler } from './ai/dynamicRescheduler.js'
import type { FarmerRequestStatus } from '@prisma/client'

export function requestDto(item: any) { return { id: item.id, farmerId: item.farmerId, requestedMachineType: item.requestedMachineType, machineType: item.requestedMachineType, areaInAcres: item.areaInAcres, cropType: item.cropType, preferredDate: item.preferredDate, preferredTimeWindow: item.preferredTimeWindow, location: item.location, status: item.status, specialInstructions: item.specialInstructions, createdAt: item.createdAt, updatedAt: item.updatedAt, booking: item.booking ? { id: item.booking.id, machineType: item.booking.machine.type, machineName: item.booking.machine.name, operatorName: item.booking.operator?.name, scheduledStart: item.booking.scheduledStart, scheduledEnd: item.booking.scheduledEnd, status: item.booking.status } : null } }
export async function listFarmerRequests(farmerId: string, filters: { status?: FarmerRequestStatus; from?: string; to?: string }) { const where: any = { farmerId }; if (filters.status) where.status = filters.status; if (filters.from || filters.to) where.preferredDate = { ...(filters.from ? { gte: new Date(filters.from) } : {}), ...(filters.to ? { lte: new Date(`${filters.to}T23:59:59.999`) } : {}) }; const requests = await prisma.farmerRequest.findMany({ where, include: { booking: { include: { machine: true, operator: { select: { name: true } } } } }, orderBy: { createdAt: 'desc' } }); return requests.map(requestDto) }
export async function getFarmerRequest(farmerId: string, id: string) { const item = await prisma.farmerRequest.findFirst({ where: { id, farmerId }, include: { booking: { include: { machine: true, operator: { select: { name: true, phone: true } } } } } }); return item ? requestDto(item) : null }
export async function listFarmerBookings(farmerId: string, filters: { status?: string; from?: string; to?: string }) { const where: any = { farmerId }; if (filters.status) where.status = filters.status; if (filters.from || filters.to) where.scheduledStart = { ...(filters.from ? { gte: new Date(filters.from) } : {}), ...(filters.to ? { lt: new Date(`${filters.to}T23:59:59.999`) } : {}) }; const bookings = await prisma.booking.findMany({ where, include: { machine: true, operator: { select: { id: true, name: true, phone: true } } }, orderBy: { scheduledStart: 'asc' } }); return bookings.map((item) => ({ id: item.id, machineType: item.machine.type, machineName: item.machine.name, scheduledStart: item.scheduledStart, scheduledEnd: item.scheduledEnd, status: item.status, areaInAcres: item.areaInAcres, location: item.location, operatorName: item.operator?.name, operator: item.operator ? { name: item.operator.name, phone: item.operator.phone } : null, actualStart: item.actualStart, actualEnd: item.actualEnd, specialInstructions: item.specialInstructions })) }
export async function getFarmerBooking(farmerId: string, id: string) { const booking = await prisma.booking.findFirst({ where: { id, farmerId }, include: { machine: true, operator: { select: { name: true, phone: true } } } }); return booking ? { ...booking, machineType: booking.machine.type, machineName: booking.machine.name, machine: undefined, operatorName: booking.operator?.name, operator: booking.operator } : null }
export async function cancelFarmerBooking(farmerId: string, id: string) { const booking = await prisma.booking.findFirst({ where: { id, farmerId } }); if (!booking) return { error: 'NOT_FOUND' as const }; if (!['APPROVED', 'ASSIGNED'].includes(booking.status) || booking.actualStart) return { error: 'CANNOT_CANCEL' as const }; const updated = await prisma.booking.update({ where: { id }, data: { status: 'CANCELLED' } }); await notifyBookingEvent(updated, 'JOB_CANCELLED', 'Booking cancelled', 'Your booking was cancelled successfully.'); void dynamicRescheduler.propose('CANCELLATION', { machineId: booking.machineId, date: booking.scheduledStart.toISOString().slice(0, 10) }).catch(() => undefined); return { booking: updated }
}
export async function approveFarmerRequest(requestId: string, input: { machineId: string; operatorId?: string; scheduledStart: Date; scheduledEnd: Date }) { const request = await prisma.farmerRequest.findUnique({ where: { id: requestId } }); if (!request) return null; const location = request.location === null ? Prisma.JsonNull : request.location as Prisma.InputJsonValue; const booking = await prisma.booking.create({ data: { farmerId: request.farmerId, machineId: input.machineId, operatorId: input.operatorId, areaInAcres: request.areaInAcres, cropType: request.cropType, location, scheduledStart: input.scheduledStart, scheduledEnd: input.scheduledEnd, status: input.operatorId ? 'ASSIGNED' : 'APPROVED', specialInstructions: request.specialInstructions }, include: { machine: true, operator: { select: { name: true } } } }); await prisma.farmerRequest.update({ where: { id: request.id }, data: { status: booking.status, bookingId: booking.id } }); await notifyFarmer({ farmerId: request.farmerId, type: 'REQUEST_APPROVED', title: 'Request approved', message: 'Your machinery request has been approved by the CHC.', relatedRequestId: request.id, relatedBookingId: booking.id }); await notifyBookingEvent(booking, input.operatorId ? 'JOB_ASSIGNED' : 'JOB_SCHEDULED', input.operatorId ? 'Operator assigned' : 'Job scheduled', input.operatorId ? 'An operator has been assigned to your booking.' : 'Your booking has been scheduled by the CHC.'); return booking }
