import fs from 'node:fs/promises'
import type { Express } from 'express'
import { Prisma } from '@prisma/client'
import { prisma } from '../lib/prisma.js'
import { jobDurationPredictor } from './ai/jobDurationPredictor.js'
import { AppError } from '../utils/errors.js'
import { translateTamilToEnglish } from './ai/tamilTranslator.js'
function parseTimeWindow(text: string) { const explicit = text.match(/(\d{1,2}(?::\d{2})?)\s*(?:am|pm)?\s*(?:to|-|until)\s*(\d{1,2}(?::\d{2})?)\s*(am|pm)?/i); if (explicit) return `${explicit[1]} - ${explicit[2]}${explicit[3] ? ` ${explicit[3]}` : ''}`; if (/afternoon|மதியம்/i.test(text)) return '12:00 - 16:00'; if (/evening|மாலை/i.test(text)) return '16:00 - 18:00'; return '07:30 - 09:30' }
function parseDate(text: string) { const explicit = text.match(/(?:on|for)?\s*(\d{1,2})(?:st|nd|rd|th)?\s*(january|february|march|april|may|june|july|august|september|october|november|december)/i); if (explicit) return new Date(`${explicit[2]} ${explicit[1]}, ${new Date().getFullYear()}`).toISOString().slice(0, 10); return /tomorrow|நாளை/i.test(text) ? new Date(Date.now() + 86400000).toISOString().slice(0, 10) : new Date().toISOString().slice(0, 10) }
export function extractBookingData(transcript: string) { const phone = transcript.match(/(?:\+91[\s-]?)?[6-9]\d{9}/)?.[0] || ''; const area = transcript.match(/(\d+(?:\.\d+)?)\s*(?:acre|acres)/i)?.[1] || ''; const machine = ['tractor', 'rotavator', 'seeder', 'sprayer', 'harvester'].find((name) => transcript.toLowerCase().includes(name)) || 'tractor'; const farmerName = transcript.match(/^([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,2})\s+requested/i)?.[1] || transcript.match(/(?:farmer|name)\s*(?:is|:)?\s*([A-Z][a-z]+(?:\s+[A-Z][a-z]+){1,2})/i)?.[1] || ''; const village = (transcript.match(/\b(?:village|at|in)\b\s+([A-Za-z][A-Za-z ]{2,30}?)(?=\s+(?:field|plot|near|on|for)|,|$)/i)?.[1]?.trim() || '').replace(/\s+village$/i, ''); const field = transcript.match(/\b(?:field|plot)\b\s*(?:is|:)?\s*([A-Za-z0-9][A-Za-z0-9 -]{1,24}?)(?=\s+(?:near|on|at)|,|$)/i)?.[1]?.trim() || ''; const landmark = transcript.match(/\b(?:near|landmark)\b\s+([A-Za-z][A-Za-z ]{2,30}?)(?=\s+(?:on|for)|,|$)/i)?.[1]?.trim() || ''; const location = { village, field, landmark }; const preferredTimeWindow = parseTimeWindow(transcript); return { farmerName, farmerPhone: phone, phone, machineType: machine, areaInAcres: Number(area) || 1, preferredDate: parseDate(transcript), preferredTimeWindow, timeWindow: preferredTimeWindow, location, village, field, landmark, specialNotes: transcript, notes: transcript } }
export async function transcribeAudio(file: Express.Multer.File, suppliedTranscript?: string, sourceLanguage = 'en-IN') { if (!file) throw new AppError(400, 'AUDIO_REQUIRED', 'Audio file is required.'); if (suppliedTranscript?.trim()) return sourceLanguage.toLowerCase().startsWith('ta') ? translateTamilToEnglish(suppliedTranscript) : suppliedTranscript; // Replace this deterministic stub with the configured speech provider.
  await fs.access(file.path); return 'Meena Devi requested a tractor for 4 acres in Bairiya village. Please call on arrival near the tube well.' }
export async function processAudio(file: Express.Multer.File, suppliedTranscript?: string, sourceLanguage?: string) { const transcript = await transcribeAudio(file, suppliedTranscript, sourceLanguage); const extractedData = extractBookingData(transcript); const recording = await prisma.voiceRecording.create({ data: { audioUrl: file.path, transcript, extractedData, status: 'PROCESSING' } }); return { voiceRecordingId: recording.id, extractedData, transcript } }
export async function confirmRecording(id: string, extractedData: Record<string, unknown>, chclId?: string | null) { const recording = await prisma.voiceRecording.findUnique({ where: { id } }); if (!recording || recording.status !== 'PROCESSING') throw new AppError(409, 'VOICE_RECORDING_UNAVAILABLE', 'Voice recording is no longer available.'); const phone = String(extractedData.farmerPhone || extractedData.phone || ''); const name = String(extractedData.farmerName || 'Farmer'); let farmer = await prisma.user.findFirst({ where: { phone, role: 'FARMER' } }); if (!farmer) farmer = await prisma.user.create({ data: { name, phone, email: `${phone.replace(/\D/g, '')}@farmer.farmfleet.local`, role: 'FARMER', passwordHash: 'managed-by-chc', chclId } }); const timeWindow = String(extractedData.preferredTimeWindow || extractedData.timeWindow || '07:30 - 09:30'); const start = new Date(`${String(extractedData.preferredDate)}T${timeWindow.split(' - ')[0]}:00`); const end = new Date(`${String(extractedData.preferredDate)}T${timeWindow.split(' - ')[1]}:00`); const location = (extractedData.location && typeof extractedData.location === 'object' ? extractedData.location : { village: extractedData.village, field: extractedData.field, landmark: extractedData.landmark }) as { village?: string; field?: string; landmark?: string }; const machine = await prisma.machine.findFirst({ where: { type: String(extractedData.machineType || 'tractor'), ...(chclId ? { chclId } : {}) } }); if (!machine) throw new AppError(409, 'MACHINE_UNAVAILABLE', 'No matching machine is available.'); const prediction = await jobDurationPredictor.predict({ machineType: machine.type, areaInAcres: Number(extractedData.areaInAcres || 1), location }); const booking = await prisma.booking.create({ data: { farmerId: farmer.id, machineId: machine.id, areaInAcres: Number(extractedData.areaInAcres || 1), location: { village: String(location.village || ''), field: String(location.field || ''), landmark: String(location.landmark || '') }, scheduledStart: start, scheduledEnd: end, predictedDurationMinutes: prediction.predictedDurationMinutes, specialInstructions: String(extractedData.specialNotes || extractedData.notes || ''), status: 'PENDING', voiceRecordings: { connect: { id } } } }); await prisma.voiceRecording.update({ where: { id }, data: { status: 'CONFIRMED', bookingId: booking.id } }); return booking }
export async function rejectRecording(id: string) { const recording = await prisma.voiceRecording.update({ where: { id }, data: { status: 'REJECTED', transcript: null, extractedData: Prisma.JsonNull } }); await fs.rm(recording.audioUrl, { force: true }); return { id: recording.id, status: recording.status } }
