import express from 'express'
import cors from 'cors'
import morgan from 'morgan'
import { config } from './config.js'
import authRoutes from './routes/authRoutes.js'
import bookingRoutes from './routes/bookingRoutes.js'
import voiceRoutes from './routes/voiceRoutes.js'
import scheduleRoutes from './routes/scheduleRoutes.js'
import farmerRoutes from './routes/farmerRoutes.js'
import operatorRoutes from './routes/operatorRoutes.js'
import machineRoutes from './routes/machineRoutes.js'
import aiRoutes from './routes/aiRoutes.js'
import chatRoutes from './routes/chatRoutes.js'
import userRoutes from './routes/userRoutes.js'
import { errorHandler, notFound } from './middleware/errorHandler.js'
const app = express(); app.use(cors({ origin: config.CLIENT_ORIGIN })); app.use(express.json({ limit: '1mb' })); app.use(morgan('combined')); app.get('/health', (_request, response) => response.json({ status: 'ok', service: 'farmfleet-api' })); app.use('/api/auth', authRoutes); app.use('/api/bookings', bookingRoutes); app.use('/api/machines', machineRoutes); app.use('/api/users', userRoutes); app.use('/api/voice-booking', voiceRoutes); app.use('/api/schedule', scheduleRoutes); app.use('/api/ai', aiRoutes); app.use('/api/chat', chatRoutes); app.use('/api/farmer', farmerRoutes); app.use('/api/operator', operatorRoutes); app.use(notFound); app.use(errorHandler); export default app
