import type { Request, Response } from 'express'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import { z } from 'zod'
import { config } from '../config.js'
import { prisma } from '../lib/prisma.js'
import { sendError } from '../utils/errors.js'
const loginSchema = z.object({ email: z.string().email(), password: z.string().min(1) })
export async function login(request: Request, response: Response) { const { email, password } = loginSchema.parse(request.body); if (!config.databaseConfigured) { const demoUsers: Record<string, { id: string; name: string; phone: string; role: 'ADMIN' | 'CHC_MANAGER' | 'OPERATOR' | 'FARMER' }> = { 'admin@farmfleet.in': { id: 'demo-admin', name: 'Vikram Mehta', phone: '+91 98765 40011', role: 'ADMIN' }, 'manager@farmfleet.in': { id: 'demo-manager', name: 'Anita Rao', phone: '+91 98765 40010', role: 'CHC_MANAGER' }, 'ravi@farmfleet.in': { id: 'demo-operator', name: 'Ravi Kumar', phone: '+91 98111 22003', role: 'OPERATOR' }, 'rajesh@farmfleet.in': { id: 'demo-farmer', name: 'Rajesh Singh', phone: '+91 98991 88773', role: 'FARMER' } }; const demo = demoUsers[email]; if (!demo || password !== 'password123') return sendError(response, 401, 'INVALID_CREDENTIALS', 'Use a FarmFleet demo account with password123.'); return response.json({ token: 'demo-token', user: { ...demo, email } }) } const user = await prisma.user.findUnique({ where: { email } }); if (!user || !user.isActive || !(await bcrypt.compare(password, user.passwordHash))) return sendError(response, 401, 'INVALID_CREDENTIALS', 'Email or password is incorrect.'); const token = jwt.sign({ sub: user.id, role: user.role, chclId: user.chclId }, config.JWT_SECRET, { expiresIn: '8h' }); return response.json({ token, user: { id: user.id, name: user.name, email: user.email, phone: user.phone, role: user.role } }) }

const profileSchema = z.object({ name: z.string().min(2).max(80).optional(), email: z.string().email().refine((value) => value.toLowerCase().endsWith('@farmfleet.in'), 'Login email must use the @farmfleet.in domain.').optional(), phone: z.string().min(7).max(20).optional(), currentPassword: z.string().optional(), newPassword: z.string().min(8).max(100).optional() }).refine((input) => !input.newPassword || input.currentPassword, { message: 'Current password is required to set a new password.', path: ['currentPassword'] })
export async function updateProfile(request: Request, response: Response) { const input = profileSchema.parse(request.body); const existing = await prisma.user.findUnique({ where: { id: request.user!.id } }); if (!existing) return sendError(response, 404, 'NOT_FOUND', 'User profile not found.'); if (input.newPassword && !(await bcrypt.compare(input.currentPassword!, existing.passwordHash))) return sendError(response, 400, 'INVALID_PASSWORD', 'Current password is incorrect.'); const passwordHash = input.newPassword ? await bcrypt.hash(input.newPassword, 10) : undefined; try { const user = await prisma.user.update({ where: { id: existing.id }, data: { name: input.name, email: input.email, phone: input.phone, passwordHash } }); return response.json({ user: { id: user.id, name: user.name, email: user.email, phone: user.phone, role: user.role } }) } catch (error: any) { if (error?.code === 'P2002') return sendError(response, 409, 'EMAIL_IN_USE', 'That email address is already in use.'); throw error } }
