import type { Request, Response } from 'express'
import { prisma } from '../lib/prisma.js'
import { bookingSchema, bookingUpdateSchema } from '../utils/validation.js'
import { createBooking, listBookings, updateBooking } from '../services/bookingService.js'
import { dynamicRescheduler } from '../services/ai/dynamicRescheduler.js'
import { sendError } from '../utils/errors.js'
export async function getBookings(request: Request, response: Response) { const query = request.query; const stringParam = (value: unknown) => typeof value === 'string' ? value : undefined; const bookings = await listBookings(request.user!, { status: stringParam(query.status) as any, date: stringParam(query.date), dateFrom: stringParam(query.dateFrom), dateTo: stringParam(query.dateTo), machine: stringParam(query.machine), farmer: stringParam(query.farmer) }); response.json(bookings) }
export async function postBooking(request: Request, response: Response) { const input = bookingSchema.parse(request.body); const booking = await createBooking(input, request.user?.chclId); if (/urgent/i.test(input.specialInstructions || '')) void dynamicRescheduler.propose('URGENT_JOB', { machineId: input.machineId, date: input.scheduledStart.toISOString().slice(0, 10) }).catch(() => undefined); response.status(201).json(booking) }
export async function getBooking(request: Request, response: Response) { const booking = await prisma.booking.findUnique({ where: { id: String(request.params.id) }, include: { farmer: true, machine: true, operator: true } }); if (!booking) return sendError(response, 404, 'NOT_FOUND', 'Booking not found.'); if (request.user?.role === 'FARMER' && booking.farmerId !== request.user.id) return sendError(response, 403, 'FORBIDDEN', 'You can only view your own bookings.'); response.json(booking) }
export async function patchBooking(request: Request, response: Response) { const input = bookingUpdateSchema.parse(request.body); const booking = await updateBooking(String(request.params.id), input); response.json(booking) }
export async function deleteBooking(request: Request, response: Response) { const id = String(request.params.id); const existing = await prisma.booking.findUnique({ where: { id } }); if (!existing) return response.status(404).json({ error: { code: 'NOT_FOUND', message: 'Booking not found.' } }); const booking = await prisma.booking.update({ where: { id }, data: { status: 'CANCELLED' } }); void dynamicRescheduler.propose('CANCELLATION', { machineId: existing.machineId, date: existing.scheduledStart.toISOString().slice(0, 10) }).catch(() => undefined); response.json({ id: booking.id, status: booking.status }) }
