import type { Request, Response } from 'express'
import bcrypt from 'bcryptjs'
import { z } from 'zod'
import { prisma } from '../lib/prisma.js'
import { sendError } from '../utils/errors.js'
import { requestSchema } from '../utils/validation.js'
import { cancelFarmerBooking, getFarmerBooking, getFarmerRequest, listFarmerBookings, listFarmerRequests, requestDto } from '../services/farmerService.js'

const listSchema = z.object({ status: z.string().optional(), from: z.string().optional(), to: z.string().optional() })
const profileSchema = z.object({ name: z.string().min(2).max(80).optional(), village: z.string().max(100).optional(), address: z.string().max(250).optional(), phone: z.string().min(7).max(20).optional(), currentPassword: z.string().optional(), newPassword: z.string().min(8).max(100).optional() }).refine((value) => !value.newPassword || value.currentPassword, { message: 'Current password is required to change your password.', path: ['currentPassword'] })

export async function getProfile(request: Request, response: Response) { const profile = await prisma.user.findUnique({ where: { id: request.user!.id }, select: { id: true, name: true, email: true, phone: true, village: true, address: true, role: true, createdAt: true } }); if (!profile) return sendError(response, 404, 'PROFILE_NOT_FOUND', 'Farmer profile not found.'); response.json(profile) }
export async function patchProfile(request: Request, response: Response) { const input = profileSchema.parse(request.body); const user = await prisma.user.findUnique({ where: { id: request.user!.id } }); if (!user || user.role !== 'FARMER') return sendError(response, 404, 'PROFILE_NOT_FOUND', 'Farmer profile not found.'); if (input.newPassword && !(await bcrypt.compare(input.currentPassword!, user.passwordHash))) return sendError(response, 400, 'INVALID_PASSWORD', 'Current password is incorrect.'); const passwordHash = input.newPassword ? await bcrypt.hash(input.newPassword, 10) : undefined; const updated = await prisma.user.update({ where: { id: user.id }, data: { name: input.name, phone: input.phone, village: input.village, address: input.address, passwordHash }, select: { id: true, name: true, email: true, phone: true, village: true, address: true, role: true, createdAt: true } }); response.json(updated) }

export async function getRequests(request: Request, response: Response) { response.json(await listFarmerRequests(request.user!.id, listSchema.parse(request.query) as any)) }
export async function postRequest(request: Request, response: Response) { const input = requestSchema.parse(request.body); const item = await prisma.farmerRequest.create({ data: { farmerId: request.user!.id, requestedMachineType: input.machineType, areaInAcres: input.areaInAcres, cropType: input.cropType, preferredDate: input.preferredDate, preferredTimeWindow: input.preferredTimeWindow, location: input.location, specialInstructions: input.specialInstructions, status: 'PENDING' } }); response.status(201).json(requestDto(item)) }
export async function getRequest(request: Request, response: Response) { const item = await getFarmerRequest(request.user!.id, String(request.params.id)); if (!item) return sendError(response, 404, 'REQUEST_NOT_FOUND', 'Machinery request not found.'); response.json(item) }

export async function getBookings(request: Request, response: Response) { response.json(await listFarmerBookings(request.user!.id, listSchema.parse(request.query))) }
export async function getBooking(request: Request, response: Response) { const item = await getFarmerBooking(request.user!.id, String(request.params.id)); if (!item) return sendError(response, 404, 'BOOKING_NOT_FOUND', 'Booking not found.'); response.json(item) }
export async function cancelBooking(request: Request, response: Response) { const result = await cancelFarmerBooking(request.user!.id, String(request.params.id)); if (result.error === 'NOT_FOUND') return sendError(response, 404, 'BOOKING_NOT_FOUND', 'Booking not found.'); if (result.error === 'CANNOT_CANCEL') return sendError(response, 409, 'BOOKING_CANNOT_CANCEL', 'Only approved or assigned bookings can be cancelled before work starts.'); response.json(result.booking) }

export async function getNotifications(request: Request, response: Response) { const unreadOnly = request.query.unreadOnly === 'true'; const notifications = await prisma.farmerNotification.findMany({ where: { farmerId: request.user!.id, ...(unreadOnly ? { read: false } : {}) }, orderBy: { createdAt: 'desc' } }); response.json(notifications) }
export async function markNotificationRead(request: Request, response: Response) { const id = String(request.params.id); const notification = await prisma.farmerNotification.findFirst({ where: { id, farmerId: request.user!.id } }); if (!notification) return sendError(response, 404, 'NOTIFICATION_NOT_FOUND', 'Notification not found.'); response.json(await prisma.farmerNotification.update({ where: { id }, data: { read: true } })) }
