import type { Request, Response } from 'express'
import { z } from 'zod'
import { prisma } from '../lib/prisma.js'
import { listBookings, toBookingDto } from '../services/bookingService.js'
import { recordTrainingSample } from '../services/trainingService.js'
import { dynamicRescheduler } from '../services/ai/dynamicRescheduler.js'
import { notifyBookingEvent } from '../services/notificationService.js'
export async function getTasks(request: Request, response: Response) { response.json(await listBookings(request.user!, {})) }
export async function patchTask(request: Request, response: Response) { const input = z.object({ status: z.enum(['START', 'PAUSE', 'COMPLETE', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED']), actualStart: z.coerce.date().optional(), actualEnd: z.coerce.date().optional() }).parse(request.body); const id = String(request.params.id); const existing = await prisma.booking.findFirst({ where: { id, operatorId: request.user!.id }, include: { machine: true } }); if (!existing) return response.status(404).json({ error: { code: 'NOT_FOUND', message: 'Assigned task not found.' } }); const now = new Date(); const mappedStatus = input.status === 'START' ? 'IN_PROGRESS' : input.status === 'COMPLETE' ? 'COMPLETED' : input.status === 'PAUSE' ? 'ASSIGNED' : input.status; const actualStart = input.actualStart || (input.status === 'START' ? now : undefined); const actualEnd = input.actualEnd || (input.status === 'COMPLETE' ? now : undefined); const booking = await prisma.booking.update({ where: { id }, data: { status: mappedStatus, actualStart, actualEnd }, include: { farmer: true, machine: true, operator: true } }); await prisma.farmerRequest.updateMany({ where: { bookingId: id }, data: { status: mappedStatus } }); if (booking.actualStart && booking.actualEnd) await recordTrainingSample(booking); if (mappedStatus === 'COMPLETED') await notifyBookingEvent(booking, 'JOB_COMPLETED', 'Job completed', 'Your field job has been completed.'); if (mappedStatus === 'CANCELLED') await notifyBookingEvent(booking, 'JOB_CANCELLED', 'Booking cancelled', 'Your booking has been cancelled.'); if (actualStart && actualStart.getTime() > existing.scheduledStart.getTime() + 30 * 60_000) void dynamicRescheduler.propose('DELAY', { machineId: existing.machineId, date: existing.scheduledStart.toISOString().slice(0, 10) }).catch(() => undefined); response.json(toBookingDto(booking)) }
