import type { Request, Response } from 'express'
import { z } from 'zod'
import { prisma } from '../lib/prisma.js'
import { sendError } from '../utils/errors.js'

const locationSchema = z.object({ bookingId: z.string().min(1), lat: z.number().gte(-90).lte(90), lng: z.number().gte(-180).lte(180), speed: z.number().nonnegative().optional(), timestamp: z.coerce.date().optional() })
export async function getActiveJob(request: Request, response: Response) { const booking = await prisma.booking.findFirst({ where: { operatorId: request.user!.id, status: 'IN_PROGRESS' }, include: { farmer: true, machine: true, operator: { select: { name: true, phone: true } } }, orderBy: { scheduledStart: 'asc' } }); response.json(booking ? { ...booking, machineType: booking.machine.type, machineName: booking.machine.name, farmerName: booking.farmer.name, operatorName: booking.operator?.name } : null) }
export async function postOperatorLocation(request: Request, response: Response) { const input = locationSchema.parse(request.body); const booking = await prisma.booking.findFirst({ where: { id: input.bookingId, operatorId: request.user!.id, status: 'IN_PROGRESS' } }); if (!booking) return sendError(response, 404, 'ACTIVE_JOB_NOT_FOUND', 'This job is not assigned to you or is not active.'); const point = await prisma.operatorLocation.create({ data: { bookingId: booking.id, operatorId: request.user!.id, lat: input.lat, lng: input.lng, speed: input.speed, timestamp: input.timestamp || new Date() } }); response.status(201).json(point) }
export async function getChcTracking(request: Request, response: Response) { const booking = await prisma.booking.findFirst({ where: { id: String(request.params.bookingId), ...(request.user?.chclId ? { machine: { chclId: request.user.chclId } } : {}) }, include: { farmer: { select: { name: true, phone: true } }, machine: true, operator: { select: { name: true, phone: true } } } }); if (!booking) return sendError(response, 404, 'BOOKING_NOT_FOUND', 'Booking not found.'); const locations = await prisma.operatorLocation.findMany({ where: { bookingId: booking.id }, orderBy: { timestamp: 'desc' }, take: 100 }); const latest = locations[0] || null; response.json({ booking: { id: booking.id, farmerName: booking.farmer.name, farmerPhone: booking.farmer.phone, machineType: booking.machine.type, machineName: booking.machine.name, operator: booking.operator, scheduledStart: booking.scheduledStart, scheduledEnd: booking.scheduledEnd, status: booking.status, location: booking.location }, operatorLocation: latest, path: locations.reverse() }) }
