import { ExternalLink, MapPin, Navigation, Tractor } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { getBookings, getChcTracking } from '../services/api'
import { demoBookings } from '../data'
import { Panel } from '../components/Ui'
import { StatusBadge } from '../components/StatusBadge'
import { MapComponent } from '../components/MapComponent'

export function ChcTrackingPage() { const { data = demoBookings } = useQuery({ queryKey: ['tracking-bookings'], queryFn: getBookings }); const active = data.filter((booking) => ['IN_PROGRESS', 'ASSIGNED'].includes(booking.status)); return <div className="dashboard tracking-page"><div className="page-intro"><div><span className="eyebrow">OPERATIONS / LIVE TRACKING</span><h1>Live tracking</h1><p>See active operators and their next field stop.</p></div><span className="tracking-live"><i />Updates every 10 seconds</span></div><div className="tracking-list">{active.map((booking) => <Link to={`/chc/tracking/${booking.id}`} className="tracking-card" key={booking.id}><span className="tracking-machine"><Tractor size={22} /></span><div><strong>{booking.farmerName}</strong><span><MapPin size={13} />{booking.location.village} · {booking.machineType}</span><small>{booking.operatorName || 'Operator not assigned'} · {booking.scheduledStart.slice(11, 16)}</small></div><StatusBadge status={booking.status} /><ExternalLink size={16} /></Link>)}</div>{!active.length && <Panel title="No active jobs"><div className="empty-state"><Navigation size={22} /><h3>No field jobs in progress</h3><p>Assigned and in-progress jobs will appear here.</p></div></Panel>}</div> }
export function ChcTrackingDetailPage() { const { bookingId = '' } = useParams(); const { data, isLoading } = useQuery({ queryKey: ['chc-tracking', bookingId], queryFn: () => getChcTracking(bookingId), refetchInterval: 10_000 }); if (isLoading || !data) return <div className="dashboard"><div className="loading-state"><span className="spinner dark" />Loading live location...</div></div>; const center = data.operatorLocation ? { lat: data.operatorLocation.lat, lng: data.operatorLocation.lng } : { lat: 28.9845, lng: 77.7064 }; const field = { lat: center.lat + .004, lng: center.lng + .004 }; const updated = data.operatorLocation && (Date.now() - new Date(data.operatorLocation.timestamp).getTime()) > 10 * 60 * 1000; return <div className="dashboard tracking-detail"><Link to="/chc/tracking" className="back-link">← Back to live tracking</Link><div className="page-intro"><div><span className="eyebrow">LIVE / {data.booking.id}</span><h1>{data.booking.farmerName}</h1><p>{data.booking.machineType} · {data.booking.location.village}, {data.booking.location.field}</p></div><StatusBadge status={data.booking.status} /></div>{updated && <div className="stale-warning">Location data is more than 10 minutes old. Ask the operator to check tracking.</div>}<div className="tracking-detail-grid"><div className="map-panel"><MapComponent center={center} markers={[{ lat: center.lat, lng: center.lng, label: data.booking.operatorName || 'Operator' }, { lat: field.lat, lng: field.lng, label: 'Assigned field' }]} path={data.path} polylines={data.path.length ? [{ path: data.path.map((point) => ({ lat: point.lat, lng: point.lng })) }] : []} /><div className="map-caption"><span><i className="map-key operator" />Operator location</span><span><i className="map-key field" />Assigned field</span></div></div><Panel title="Job summary"><div className="tracking-summary"><div><Tractor size={16} /><span>Machine<strong>{data.booking.machineType}</strong></span></div><div><MapPin size={16} /><span>Assigned field<strong>{data.booking.location.village}</strong><small>{data.booking.location.field} · {data.booking.location.landmark}</small></span></div><div><Navigation size={16} /><span>Operator<strong>{data.booking.operatorName || 'Not assigned'}</strong><small>{data.operatorLocation ? `Last update ${new Date(data.operatorLocation.timestamp).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}` : 'No location data received yet.'}</small></span></div></div></Panel></div></div> }
