import { ArrowLeft, CalendarDays, ChevronRight, MapPin, Phone, Tractor, X } from 'lucide-react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { cancelFarmerBooking, getFarmerBooking, getFarmerBookings } from '../services/api'
import { demoBookings } from '../data'
import { Button, Panel } from '../components/Ui'
import { StatusBadge } from '../components/StatusBadge'
import type { FarmerBooking } from '../types'

export function FarmerBookingsPage() { const { data = [] } = useQuery({ queryKey: ['farmer-bookings'], queryFn: () => getFarmerBookings() }); return <div className="dashboard farmer-page"><div className="page-intro"><div><span className="eyebrow">MY FARM / BOOKINGS</span><h1>My bookings</h1><p>Confirmed machine work, all in one place.</p></div></div><Panel title="Confirmed work"><div className="farmer-booking-list">{data.map((booking) => <Link to={`/farmer/bookings/${booking.id}`} className="farmer-booking-row" key={booking.id}><span className="booking-date"><strong>{new Date(booking.scheduledStart).toLocaleDateString('en-IN', { day: '2-digit' })}</strong><small>{new Date(booking.scheduledStart).toLocaleDateString('en-IN', { month: 'short' }).toUpperCase()}</small></span><div><strong>{booking.machineType} · {booking.areaInAcres} acres</strong><span><CalendarDays size={13} />{new Date(booking.scheduledStart).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })} · {booking.location.village}</span><small><MapPin size={12} />{booking.operatorName || 'Operator being assigned'}</small></div><StatusBadge status={booking.status} /><ChevronRight size={17} /></Link>)}</div></Panel></div> }
export function FarmerBookingDetailPage() { const { id = '' } = useParams(); const navigate = useNavigate(); const client = useQueryClient(); const { data = getDemoBooking() } = useQuery({ queryKey: ['farmer-booking', id], queryFn: () => getFarmerBooking(id) }); const cancellable = data && ['APPROVED', 'ASSIGNED'].includes(data.status) && !data.actualStart; async function cancel() { if (window.confirm('Cancel this booking?')) { await cancelFarmerBooking(id); client.invalidateQueries({ queryKey: ['farmer-booking', id] }); client.invalidateQueries({ queryKey: ['farmer-bookings'] }) } } return <div className="dashboard farmer-page"><Link to="/farmer/bookings" className="back-link"><ArrowLeft size={16} />Back to bookings</Link><div className="page-intro"><div><span className="eyebrow">BOOKING / {data.id}</span><h1>{data.machineType} work</h1><p>{data.location.village}, {data.location.field}</p></div><StatusBadge status={data.status} /></div><Panel title="Booking details"><div className="booking-detail-hero"><div className="machine-choice-icon"><Tractor size={25} /></div><div><strong>{data.machineName}</strong><span>{data.machineType} · {data.areaInAcres} acres</span></div></div><div className="detail-list"><div><CalendarDays size={16} /><span>Scheduled<strong>{new Date(data.scheduledStart).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}</strong></span></div><div><MapPin size={16} /><span>Location<strong>{data.location.village}, {data.location.field}</strong><small>{data.location.landmark}</small></span></div><div><Phone size={16} /><span>Operator<strong>{data.operatorName || 'Being assigned'}</strong>{data.operator?.phone && <small>{data.operator.phone}</small>}</span></div></div>{data.specialInstructions && <div className="detail-note">{data.specialInstructions}</div>}{cancellable && <div className="form-actions"><Button variant="danger" onClick={cancel}><X size={15} />Cancel booking</Button></div>}</Panel></div> }
function getDemoBooking(): FarmerBooking { const item = demoBookings[0]; return { id: item.id, machineType: item.machineType, machineName: item.machineType, scheduledStart: item.scheduledStart, scheduledEnd: item.scheduledEnd, status: item.status, areaInAcres: item.areaInAcres, location: item.location, operatorName: item.operatorName, operator: item.operatorName ? { name: item.operatorName, phone: '' } : null, specialInstructions: item.specialInstructions } }
