import { ArrowLeft, CalendarDays, Check, Clock3, MapPin, Phone, Tractor } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { getFarmerRequest } from '../services/api'
import { demoRequests } from '../data'
import { Panel } from '../components/Ui'
import { StatusBadge } from '../components/StatusBadge'

const stages = ['PENDING', 'APPROVED', 'ASSIGNED', 'COMPLETED']
export function FarmerRequestDetailPage() { const { id = '' } = useParams(); const { data = demoRequests[0] } = useQuery({ queryKey: ['farmer-request', id], queryFn: () => getFarmerRequest(id) }); const stageIndex = Math.max(0, stages.indexOf(data.status)); return <div className="dashboard farmer-page"><Link to="/farmer/requests" className="back-link"><ArrowLeft size={16} />Back to requests</Link><div className="page-intro"><div><span className="eyebrow">REQUEST / {data.id}</span><h1>{data.machineType[0].toUpperCase() + data.machineType.slice(1)} request</h1><p>Created {new Date(data.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' })}</p></div><StatusBadge status={data.status} /></div><Panel title="Request progress"><div className="farmer-timeline">{stages.map((stage, index) => <div className={`farmer-stage ${index <= stageIndex ? 'done' : ''}`} key={stage}><span>{index <= stageIndex ? <Check size={13} /> : index + 1}</span><strong>{stage[0] + stage.slice(1).toLowerCase()}</strong>{index < stages.length - 1 && <i />}</div>)}</div></Panel><div className="detail-grid"><Panel title="Your request"><div className="detail-list"><div><Tractor size={16} /><span>Machine<strong>{data.machineType}</strong></span></div><div><span>Area<strong>{data.areaInAcres} acres</strong></span></div><div><CalendarDays size={16} /><span>Preferred date<strong>{new Date(data.preferredDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}</strong></span></div><div><MapPin size={16} /><span>Field location<strong>{data.location.village}, {data.location.field}</strong><small>{data.location.landmark}</small></span></div></div></Panel>{data.booking ? <Panel title="Scheduled job"><div className="detail-list"><div><Tractor size={16} /><span>Assigned machine<strong>{data.booking.machineName}</strong></span></div><div><Clock3 size={16} /><span>Scheduled time<strong>{new Date(data.booking.scheduledStart).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}</strong></span></div><div><Phone size={16} /><span>Operator<strong>{data.booking.operatorName || 'Being assigned'}</strong></span></div></div></Panel> : <div className="awaiting-card"><Clock3 size={18} /><div><strong>Your CHC is reviewing this request</strong><span>We will show the operator and time here once it is assigned.</span></div></div>}</div></div> }
