import { CalendarDays, ChevronRight, Filter, MapPin, Plus, Search } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useQuery } from '@tanstack/react-query'
import { getFarmerRequests } from '../services/api'
import { demoRequests } from '../data'
import { Input, Panel, Select } from '../components/Ui'
import { StatusBadge } from '../components/StatusBadge'
import { useState } from 'react'

export function FarmerRequestsPage() {
  const [status, setStatus] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState('')
  const { data = demoRequests } = useQuery({ queryKey: ['farmer-requests', status, from, to], queryFn: () => getFarmerRequests({ status: status || undefined, from: from || undefined, to: to || undefined }) })
  return <div className="dashboard farmer-page"><div className="page-intro"><div><span className="eyebrow">MY FARM / REQUESTS</span><h1>My requests</h1><p>Track every machinery request from your phone.</p></div><Link to="/farmer/requests/new" className="button button-primary"><Plus size={17} />New request</Link></div><div className="farmer-filter"><div className="filter-label"><Filter size={15} />Filter requests</div><Select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option value="PENDING">Pending</option><option value="APPROVED">Approved</option><option value="ASSIGNED">Assigned</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option><option value="REJECTED">Rejected</option></Select><label className="farmer-date-filter"><CalendarDays size={14} /><Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} aria-label="From date" /><span>to</span><Input type="date" value={to} onChange={(e) => setTo(e.target.value)} aria-label="To date" /></label></div><Panel title={`${data.length} request${data.length === 1 ? '' : 's'}`}><div className="farmer-request-list">{data.map((request) => <Link to={`/farmer/requests/${request.id}`} className="farmer-request-card" key={request.id}><div className="farmer-request-symbol"><Search size={18} /></div><div className="farmer-request-main"><div><strong>{request.machineType[0].toUpperCase() + request.machineType.slice(1)}</strong><StatusBadge status={request.status} /></div><span>{request.areaInAcres} acres · <MapPin size={13} />{request.location.village}, {request.location.field}</span><small><CalendarDays size={13} />Preferred {new Date(request.preferredDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })} · Requested {new Date(request.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}</small></div><ChevronRight size={18} /></Link>)}</div>{!data.length && <div className="empty-state"><h3>No requests yet</h3><p>Start by telling your CHC what your field needs.</p><Link to="/farmer/requests/new" className="button button-primary">Create request</Link></div>}</Panel></div>
}
