import { ArrowLeft, CalendarDays, Check, MapPin, Plus, Tractor } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { createFarmerRequest, getFarmerRequests } from '../services/api'
import { demoRequests } from '../data'
import { Button, Field, Input, Panel, Select } from '../components/Ui'
import { StatusBadge } from '../components/StatusBadge'
import { useState } from 'react'
export function RequestsPage() { const { data = demoRequests } = useQuery({ queryKey: ['requests'], queryFn: getFarmerRequests }); return <div className="dashboard"><div className="page-intro"><div><span className="eyebrow">MY FARM / REQUESTS</span><h1>Machinery requests</h1><p>Keep an eye on the work planned for your fields.</p></div><Link to="/requests/new" className="button button-primary"><Plus size={17} />New request</Link></div><div className="request-status-line"><div className="request-step complete"><span><Check size={14} /></span><strong>Request</strong></div><div className="step-line complete" /><div className="request-step complete"><span><Check size={14} /></span><strong>Approval</strong></div><div className="step-line" /><div className="request-step"><span>3</span><strong>Assignment</strong></div><div className="step-line" /><div className="request-step"><span>4</span><strong>Field work</strong></div></div><Panel title="Your requests"><div className="request-list large">{data.map((request) => <div className="request-row" key={request.id}><div className="request-machine"><Tractor size={20} /></div><div className="request-copy"><strong>{request.machineType[0].toUpperCase() + request.machineType.slice(1)} · {request.areaInAcres} acres</strong><span><MapPin size={14} />{request.location.village}, {request.location.field}</span><small><CalendarDays size={13} />Requested {new Date(request.createdAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })} · Preferred {new Date(request.preferredDate).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' })}</small></div><StatusBadge status={request.status} /><span className="request-arrow">›</span></div>)}</div></Panel></div> }
export function RequestEditorPage() { const navigate = useNavigate(); const client = useQueryClient(); const [form, setForm] = useState({ machineType: 'tractor', area: '', date: '2025-01-20', village: '', field: '', landmark: '' }); const [saving, setSaving] = useState(false); function set(key: string, value: string) { setForm((current) => ({ ...current, [key]: value })) } async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); await createFarmerRequest({ machineType: form.machineType, areaInAcres: Number(form.area), preferredDate: form.date, location: { village: form.village, field: form.field, landmark: form.landmark }, status: 'PENDING' }); client.invalidateQueries({ queryKey: ['requests'] }); navigate('/requests') } return <div className="dashboard editor-page"><Link to="/requests" className="back-link"><ArrowLeft size={16} />Back to requests</Link><div className="page-intro"><div><span className="eyebrow">NEW FARM REQUEST</span><h1>Request a machine</h1><p>Tell your CHC what the field needs.</p></div></div><section className="editor-form-panel farmer-form"><div className="form-panel-head"><div><h2>Field work details</h2><span>Your CHC will confirm availability and a time.</span></div></div><form onSubmit={submit} className="form-layout"><div className="form-grid"><Field label="Machine type"><Select value={form.machineType} onChange={(e) => set('machineType', e.target.value)}>{['tractor', 'rotavator', 'seeder', 'sprayer', 'harvester'].map((machine) => <option key={machine}>{machine[0].toUpperCase() + machine.slice(1)}</option>)}</Select></Field><Field label="Area (acres)"><Input required type="number" step="0.1" min="0.1" value={form.area} onChange={(e) => set('area', e.target.value)} placeholder="How many acres?" /></Field></div><Field label="Preferred date"><Input required type="date" value={form.date} onChange={(e) => set('date', e.target.value)} /></Field><div className="subsection-heading"><MapPin size={17} />Where is the field?</div><div className="form-grid three"><Field label="Village"><Input required value={form.village} onChange={(e) => set('village', e.target.value)} /></Field><Field label="Field / plot"><Input required value={form.field} onChange={(e) => set('field', e.target.value)} placeholder="Plot or field name" /></Field><Field label="Landmark"><Input value={form.landmark} onChange={(e) => set('landmark', e.target.value)} placeholder="Optional" /></Field></div><div className="form-actions"><Button type="button" variant="ghost" onClick={() => navigate('/requests')}>Cancel</Button><Button disabled={saving}>{saving ? 'Sending request...' : 'Send request'}</Button></div></form></section></div> }
