import { KeyRound, Mail, Phone, Save, UserRound } from 'lucide-react'
import { useState } from 'react'
import { useAuth } from '../contexts/AuthContext'
import { Button, Field, Input, Panel } from '../components/Ui'
import '../settings.css'

export function SettingsPage() {
  const { user, updateUser } = useAuth()
  const [form, setForm] = useState({ name: user?.name || '', email: user?.email || '', phone: user?.phone || '', currentPassword: '', newPassword: '', confirmPassword: '' })
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const [error, setError] = useState('')
  function set(key: string, value: string) { setForm((current) => ({ ...current, [key]: value })) }
  async function submit(event: React.FormEvent) { event.preventDefault(); setMessage(''); setError(''); if (form.newPassword && form.newPassword !== form.confirmPassword) { setError('New passwords do not match.'); return } setSaving(true); try { await updateUser({ name: form.name, email: form.email, phone: form.phone, currentPassword: form.currentPassword || undefined, newPassword: form.newPassword || undefined }); setForm((current) => ({ ...current, currentPassword: '', newPassword: '', confirmPassword: '' })); setMessage('Profile and login details updated.') } catch (err) { setError(err instanceof Error ? err.message : 'Could not update your profile.') } finally { setSaving(false) } }
  return <div className="dashboard settings-page"><div className="page-intro"><div><span className="eyebrow">ACCOUNT / MY PROFILE</span><h1>Profile settings</h1><p>Update the name and login details used by FarmFleet.</p></div></div><div className="settings-grid"><Panel title="Personal details"><form className="form-layout" onSubmit={submit}><div className="settings-avatar"><span className="avatar large">{user?.name.split(' ').map((part) => part[0]).join('').slice(0, 2)}</span><div><strong>{user?.role === 'CHC_MANAGER' ? 'CHC Manager' : user?.role}</strong><small>Visible to your CHC team</small></div></div><Field label="Username / display name" hint="This is the name your team sees."><div className="input-with-icon"><UserRound size={16} /><Input required value={form.name} onChange={(e) => set('name', e.target.value)} /></div></Field><Field label="Login username (email prefix)" hint="Only the name before @farmfleet.in can change."><div className="input-with-icon"><Mail size={16} /><Input required type="email" pattern="[a-zA-Z0-9._%+-]+@farmfleet\.in" title="Use an email ending in @farmfleet.in" value={form.email} onChange={(e) => set('email', e.target.value)} /></div></Field><Field label="Phone number"><div className="input-with-icon"><Phone size={16} /><Input required value={form.phone} onChange={(e) => set('phone', e.target.value)} /></div></Field><div className="settings-divider"><KeyRound size={17} /><div><strong>Change password</strong><span>Leave these fields blank to keep your current password.</span></div></div><Field label="Current password"><Input type="password" value={form.currentPassword} onChange={(e) => set('currentPassword', e.target.value)} placeholder="Required to change password" /></Field><div className="form-grid"><Field label="New password"><Input minLength={8} type="password" value={form.newPassword} onChange={(e) => set('newPassword', e.target.value)} placeholder="At least 8 characters" /></Field><Field label="Confirm new password"><Input minLength={8} type="password" value={form.confirmPassword} onChange={(e) => set('confirmPassword', e.target.value)} /></Field></div>{error && <div className="form-error">{error}</div>}{message && <div className="form-success">{message}</div>}<div className="form-actions"><Button type="submit" disabled={saving}><Save size={16} />{saving ? 'Saving changes...' : 'Save profile'}</Button></div></form></Panel><aside className="settings-aside"><div className="aside-note"><span className="eyebrow">ACCOUNT SAFETY</span><h3>Your access stays yours.</h3><p>Passwords are stored securely. Changing your email updates the address you use to sign in next time.</p></div><div className="aside-tip"><strong>Password checklist</strong><ul><li>Use at least 8 characters</li><li>Do not reuse a shared CHC password</li><li>Keep your phone number current for dispatch</li></ul></div></aside></div></div>
}
